/**
 * Extension API Schemas
 *
 * Zod schemas for extension manifest validation and JSON Schema generation.
 */

// Manifest schema (main export)
export {
  ExtensionManifestSchema,
  PlatformSchema,
  AuthorSchema,
  EnginesSchema,
  type ExtensionManifest,
  type Platform,
  type Author,
  type Engines,
} from './manifest.schema.js'

// Permission schemas
export {
  PermissionSchema,
  NetworkPermissionSchema,
  StoragePermissionSchema,
  UserDataPermissionSchema,
  CapabilityPermissionSchema,
  SystemPermissionSchema,
  isValidPermission,
  VALID_PERMISSIONS,
  PERMISSION_PATTERNS,
  type Permission,
  type NetworkPermission,
  type StoragePermission,
  type UserDataPermission,
  type CapabilityPermission,
  type SystemPermission,
} from './permissions.schema.js'

// Contribution schemas
export {
  ExtensionContributionsSchema,
  LocalizedStringSchema,
  SettingDefinitionSchema,
  SettingOptionsMappingSchema,
  SettingCreateMappingSchema,
  SettingValidationSchema,
  ToolSettingsViewDefinitionSchema,
  ToolSettingsViewSchema,
  ToolSettingsListViewSchema,
  ToolSettingsComponentViewSchema,
  ToolSettingsListMappingSchema,
  ToolSettingsActionDataSourceSchema,
  PanelDefinitionSchema,
  PanelViewSchema,
  PanelComponentViewSchema,
  PanelUnknownViewSchema,
  PanelActionDataSourceSchema,
  ProviderDefinitionSchema,
  ProviderConfigSchemaSchema,
  ProviderConfigPropertySchema,
  ProviderConfigPropertyTypeSchema,
  ProviderConfigSelectOptionSchema,
  ProviderConfigValidationSchema,
  ToolDefinitionSchema,
  CommandDefinitionSchema,
  PromptContributionSchema,
  PromptSectionSchema,
  type ExtensionContributions,
  type LocalizedString,
  type SettingDefinition,
  type SettingOptionsMapping,
  type SettingCreateMapping,
  type SettingValidation,
  type ToolSettingsViewDefinition,
  type ToolSettingsView,
  type ToolSettingsListView,
  type ToolSettingsComponentView,
  type ToolSettingsListMapping,
  type ToolSettingsActionDataSource,
  type PanelDefinition,
  type PanelView,
  type PanelComponentView,
  type PanelUnknownView,
  type PanelActionDataSource,
  type ProviderDefinition,
  type ProviderConfigSchema,
  type ProviderConfigProperty,
  type ProviderConfigPropertyType,
  type ProviderConfigSelectOption,
  type ProviderConfigValidation,
  type ToolDefinition,
  type CommandDefinition,
  type PromptContribution,
  type PromptSection,
} from './contributions.schema.js'

// Component schemas
export {
  ExtensionComponentDataSchema,
  ExtensionComponentStyleSchema,
  ExtensionActionCallSchema,
  ExtensionActionRefSchema,
  ExtensionComponentIteratorSchema,
  ExtensionComponentChildrenSchema,
  ExtensionDataSourceSchema,
  AllowedCSSPropertySchema,
  IconButtonTypeSchema,
  PillVariantSchema,
  PanelActionSchema,
  HeaderPropsSchema,
  LabelPropsSchema,
  ParagraphPropsSchema,
  ButtonPropsSchema,
  TextInputPropsSchema,
  DateTimeInputPropsSchema,
  SelectPropsSchema,
  VerticalStackPropsSchema,
  HorizontalStackPropsSchema,
  GridPropsSchema,
  DividerPropsSchema,
  IconPropsSchema,
  IconButtonPropsSchema,
  PanelPropsSchema,
  TogglePropsSchema,
  CollapsiblePropsSchema,
  PillPropsSchema,
  CheckboxPropsSchema,
  MarkdownPropsSchema,
  ModalPropsSchema,
  ConditionalGroupPropsSchema,
  type ExtensionComponentData,
  type ExtensionComponentStyle,
  type ExtensionActionCall,
  type ExtensionActionRef,
  type ExtensionComponentIterator,
  type ExtensionComponentChildren,
  type ExtensionDataSource,
  type AllowedCSSProperty,
  type IconButtonType,
  type PillVariant,
  type PanelAction,
  type HeaderProps,
  type LabelProps,
  type ParagraphProps,
  type ButtonProps,
  type TextInputProps,
  type DateTimeInputProps,
  type SelectProps,
  type VerticalStackProps,
  type HorizontalStackProps,
  type GridProps,
  type DividerProps,
  type IconProps,
  type IconButtonProps,
  type PanelProps,
  type ToggleProps,
  type CollapsibleProps,
  type PillProps,
  type CheckboxProps,
  type MarkdownProps,
  type ModalProps,
  type ConditionalGroupProps,
} from './components.schema.js'
