/**
 * Memory types — see docs/redesign-2026/02-data-model.md §Memory and
 * docs/redesign-2026/03-memory.md.
 *
 * Three kinds of memory:
 * - StandingInstruction: actively applied at thread start, drives Stina's
 *   future behavior in matching contexts. User-facing label: "viktigt minne".
 * - ProfileFact: stable facts retrieved on demand. User-facing label:
 *   "faktaminne".
 * - ThreadSummary: internal index used by `recall` to find past threads. Not
 *   surfaced to the user as a "memory" type.
 */

/**
 * Scope describes when a standing instruction applies. The `match` field is
 * an optional structured hint for Stina's LLM-judged matching at event time —
 * it is *not* a binding match algorithm. See §03 "Standing-instruction
 * matching".
 */
export interface InstructionScope {
  channels?: ('mail' | 'calendar' | 'all')[]
  match?: Record<string, unknown>
}

/**
 * Conditions that invalidate a standing instruction.
 *
 * - date_passed: auto-invalidates when the date is reached
 * - event: auto-invalidates if the named signal is observed
 * - user_says: Stina-judged with confidence threshold; flagged for user
 *   confirmation, never auto-invalidates
 */
export type InvalidationCondition =
  | { kind: 'date_passed'; at: number }
  | { kind: 'user_says'; pattern: string }
  | { kind: 'event'; signal: string }

/**
 * Active rule that should be applied automatically in matching contexts.
 *
 * Lifecycle:
 * - created_by 'user': content is immutable to dream pass
 * - created_by 'stina': dream pass may edit, expire, or delete (with audit
 *   trail)
 *
 * `valid_until` may always be honored by dream pass (auto-expire is *user
 * intent*, not overwrite). The runtime asserts `created_by !== 'user'` for
 * any dream-pass-origin content mutation.
 */
export interface StandingInstruction {
  id: string
  rule: string
  scope: InstructionScope
  valid_from: number
  valid_until: number | null
  invalidate_on: InvalidationCondition[]
  source_thread_id: string | null
  created_at: number
  created_by: 'user' | 'stina'
}

/**
 * Stable fact about the user, their relationships, or preferences.
 * Retrieved on demand via `recall`; not actively applied.
 *
 * Conflict resolution (per §03):
 * - memory ↔ memory: more recent last_referenced_at wins; tie-break by
 *   created_by ('user' beats 'stina', non-dream-pass beats dream-pass)
 * - memory ↔ extension: extension wins
 * - memory ↔ user: user wins immediately, memory is updated
 */
export interface ProfileFact {
  id: string
  fact: string
  /** Subject the fact is about. "user", a person ref, etc. */
  subject: string
  /** Predicate (free-text in v1; controlled-vocabulary deferred per §03). */
  predicate: string
  source_thread_id: string | null
  last_referenced_at: number
  created_at: number
  created_by: 'user' | 'stina'
}

/**
 * Summary of a thread, generated by the dream pass when the thread becomes
 * quiet. Used by `recall` to find relevant past conversations.
 *
 * `message_count_at_generation` is used by the dream pass to detect stale
 * summaries (re-summarize threshold: > 5 new user-meaningful messages or
 * > 50% growth, whichever is smaller; silent dream-pass messages excluded).
 */
export interface ThreadSummary {
  thread_id: string
  summary: string
  topics: string[]
  generated_at: number
  message_count_at_generation: number
}
