/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProviderModal: typeof import('./src/components/settings/AddProviderModal.vue')['default']
    AddServerForm: typeof import('./src/components/tools/AddServerForm.vue')['default']
    AdvancedSettings: typeof import('./src/components/settings/AdvancedSettings.vue')['default']
    AIProviderSettings: typeof import('./src/components/settings/AIProviderSettings.vue')['default']
    AISettings: typeof import('./src/components/settings/AISettings.vue')['default']
    Avatar: typeof import('./src/components/chat/Avatar.vue')['default']
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    ChatBubble: typeof import('./src/components/chat/ChatBubble.vue')['default']
    ChatMessageHeader: typeof import('./src/components/chat/ChatMessageHeader.vue')['default']
    ChatToolbar: typeof import('./src/components/chat/ChatToolbar.vue')['default']
    EntityList: typeof import('./src/components/settings/EntityList.vue')['default']
    FormButtonSelect: typeof import('./src/components/form/FormButtonSelect.vue')['default']
    FormCheckbox: typeof import('./src/components/form/FormCheckbox.vue')['default']
    FormDate: typeof import('./src/components/form/FormDate.vue')['default']
    FormHeader: typeof import('./src/components/common/FormHeader.vue')['default']
    FormInputText: typeof import('./src/components/form/FormInputText.vue')['default']
    FormSelect: typeof import('./src/components/form/FormSelect.vue')['default']
    FormTextArea: typeof import('./src/components/form/FormTextArea.vue')['default']
    FormTime: typeof import('./src/components/form/FormTime.vue')['default']
    IconButton: typeof import('./src/components/ui/IconButton.vue')['default']
    IconToggleButton: typeof import('./src/components/ui/IconToggleButton.vue')['default']
    IHugeiconsChat01: typeof import('~icons/hugeicons/chat01')['default']
    IHugeiconsSettings02: typeof import('~icons/hugeicons/settings02')['default']
    IHugeiconsWrench01: typeof import('~icons/hugeicons/wrench01')['default']
    InteractionList: typeof import('./src/components/chat/InteractionList.vue')['default']
    InterfaceSettings: typeof import('./src/components/settings/InterfaceSettings.vue')['default']
    LanguageSelector: typeof import('./src/components/settings/LanguageSelector.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    MarkDown: typeof import('./src/components/MarkDown.vue')['default']
    MemoryList: typeof import('./src/components/settings/MemoryList.vue')['default']
    MessageInput: typeof import('./src/components/chat/MessageInput.vue')['default']
    NavButtonBase: typeof import('./src/components/nav/NavButtonBase.vue')['default']
    NavButtonIcon: typeof import('./src/components/nav/NavButtonIcon.vue')['default']
    NavButtonText: typeof import('./src/components/nav/NavButtonText.vue')['default']
    NotificationSettings: typeof import('./src/components/settings/NotificationSettings.vue')['default']
    PersonalitySettings: typeof import('./src/components/settings/PersonalitySettings.vue')['default']
    ProfileSettings: typeof import('./src/components/settings/ProfileSettings.vue')['default']
    ProjectForm: typeof import('./src/components/settings/ProjectForm.vue')['default']
    ProviderList: typeof import('./src/components/settings/ProviderList.vue')['default']
    SettingsPanel: typeof import('./src/components/common/SettingsPanel.vue')['default']
    SettingsSidebar: typeof import('./src/components/settings/SettingsSidebar.vue')['default']
    SideNav: typeof import('./src/components/nav/SideNav.vue')['default']
    SimpleButton: typeof import('./src/components/buttons/SimpleButton.vue')['default']
    SubFormHeader: typeof import('./src/components/common/SubFormHeader.vue')['default']
    ThemeSelector: typeof import('./src/components/settings/ThemeSelector.vue')['default']
    TodoPanel: typeof import('./src/components/todos/TodoPanel.vue')['default']
    'TodoPanel.EditModal': typeof import('./src/components/todos/TodoPanel.EditModal.vue')['default']
    'TodoPanel.Header': typeof import('./src/components/todos/TodoPanel.Header.vue')['default']
    'TodoPanel.Todo': typeof import('./src/components/todos/TodoPanel.Todo.vue')['default']
    ToolItem: typeof import('./src/components/tools/ToolItem.vue')['default']
    ToolServerCard: typeof import('./src/components/tools/ToolServerCard.vue')['default']
    WeatherSettings: typeof import('./src/components/settings/WeatherSettings.vue')['default']
    WorkSettings: typeof import('./src/components/settings/WorkSettings.vue')['default']
    'WorkSettings.ProjectForm': typeof import('./src/components/settings/WorkSettings.ProjectForm.vue')['default']
    'WorkSettings.ProjectList': typeof import('./src/components/settings/WorkSettings.ProjectList.vue')['default']
    'WorkSettings.Recurring': typeof import('./src/components/settings/WorkSettings.Recurring.vue')['default']
    'WorkSettings.TodoSettings': typeof import('./src/components/settings/WorkSettings.TodoSettings.vue')['default']
  }
}
