/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProviderModal: typeof import('./src/components/settings/AddProviderModal.vue')['default']
    AddServerForm: typeof import('./src/components/tools/AddServerForm.vue')['default']
    AdvancedSettings: typeof import('./src/components/settings/AdvancedSettings.vue')['default']
    AIProviderSettings: typeof import('./src/components/settings/AIProviderSettings.vue')['default']
    AISettings: typeof import('./src/components/settings/AISettings.vue')['default']
    Avatar: typeof import('./src/components/chat/Avatar.vue')['default']
    ChatBubble: typeof import('./src/components/chat/ChatBubble.vue')['default']
    ChatToolbar: typeof import('./src/components/chat/ChatToolbar.vue')['default']
    IconButton: typeof import('./src/components/ui/IconButton.vue')['default']
    IconToggleButton: typeof import('./src/components/ui/IconToggleButton.vue')['default']
    IHugeiconsChat01: typeof import('~icons/hugeicons/chat01')['default']
    IHugeiconsSettings02: typeof import('~icons/hugeicons/settings02')['default']
    IHugeiconsWrench01: typeof import('~icons/hugeicons/wrench01')['default']
    InterfaceSettings: typeof import('./src/components/settings/InterfaceSettings.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    MessageInput: typeof import('./src/components/chat/MessageInput.vue')['default']
    ProfileSettings: typeof import('./src/components/settings/ProfileSettings.vue')['default']
    ProviderList: typeof import('./src/components/settings/ProviderList.vue')['default']
    SettingsSidebar: typeof import('./src/components/settings/SettingsSidebar.vue')['default']
    SideNav: typeof import('./src/components/nav/SideNav.vue')['default']
    ThemeSelector: typeof import('./src/components/settings/ThemeSelector.vue')['default']
    TodoPanel: typeof import('./src/components/todos/TodoPanel.vue')['default']
    ToolItem: typeof import('./src/components/tools/ToolItem.vue')['default']
    ToolServerCard: typeof import('./src/components/tools/ToolServerCard.vue')['default']
  }
}
