/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIProviderSettings: typeof import('./src/components/settings/AIProviderSettings.vue')['default']
    Avatar: typeof import('./src/components/chat/Avatar.vue')['default']
    ChatBubble: typeof import('./src/components/chat/ChatBubble.vue')['default']
    ChatToolbar: typeof import('./src/components/chat/ChatToolbar.vue')['default']
    ChatView: typeof import('./src/components/chat/ChatView.vue')['default']
    IconButton: typeof import('./src/components/ui/IconButton.vue')['default']
    IconToggleButton: typeof import('./src/components/ui/IconToggleButton.vue')['default']
    IHugeiconsChat01: typeof import('~icons/hugeicons/chat01')['default']
    IHugeiconsChatDots: typeof import('~icons/hugeicons/chat-dots')['default']
    IHugeiconsCheckList: typeof import('~icons/hugeicons/check-list')['default']
    IHugeiconsLassoTool01: typeof import('~icons/hugeicons/lasso-tool01')['default']
    IHugeiconsSettings02: typeof import('~icons/hugeicons/settings02')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    MessageInput: typeof import('./src/components/chat/MessageInput.vue')['default']
    SideNav: typeof import('./src/components/nav/SideNav.vue')['default']
    ThemeSelector: typeof import('./src/components/settings/ThemeSelector.vue')['default']
    TodoPanel: typeof import('./src/components/todos/TodoPanel.vue')['default']
  }
}
