export { ChatMigrator } from './ChatMigrator.js'
export type { ChatMigratorStats } from './ChatMigrator.js'
export { MigrationRunner } from './MigrationRunner.js'
export type { MigrationRunnerOptions, MigrationResult } from './MigrationRunner.js'
export { ensureSchemaVersionsTable, recordSchemaVersion, hasSchemaVersion } from './schemaVersions.js'
export { runSanityChecks, checkFkIntegrity, checkAllArchived } from './sanityChecks.js'
export { BackupWriter } from './BackupWriter.js'
export type { BackupWriterOptions, BackupResult } from './BackupWriter.js'
export { MigrationInterruptedError } from './MigrationInterruptedError.js'
export { runMigrationIfNeeded } from './runMigrationIfNeeded.js'
export type { RunMigrationOptions } from './runMigrationIfNeeded.js'
